#ifndef MATHPARSER_DEFINITIONSMULTILATERALACTIONCALCULATOR_H
#define MATHPARSER_DEFINITIONSMULTILATERALACTIONCALCULATOR_H

#define MULTILATERAL_APPROVAL_MESSAGE "Action approved"
#define MULTILATERAL_REJECTION_MESSAGE "Action rejected"
#define MULTILATERAL_REQUEST_MESSAGE "Requesting action"
#define MULTILATERAL_AMEND_MESSAGE "Amending action"
#define MULTILATERAL_APPROVED_INPUT_NAME "Name for an approved input"
#define MULTILATERAL_AMEND_PREVIOUS_VALUE "Previous proposed value"


#endif //MATHPARSER_DEFINITIONSMULTILATERALACTIONCALCULATOR_H
