
#define TIME_VS_MONEY_PLAYER_NAME "Player 1"
#define TIME_VS_MONEY_PLAYER_OWNER "World"
#define TIME_VS_MONEY_MONEY_RESOURCE_NAME "Money"
#define TIME_VS_MONEY_MONEY_INITIAL_VALUE 100.0
#define TIME_VS_MONEY_KNOWLEDGE_RESOURCE_NAME "Knowledge"
#define TIME_VS_MONEY_KNOWLEDGE_INITIAL_VALUE 0.0
#define TIME_VS_MONEY_TIME_RESOURCE_NAME "Available time"
#define TIME_VS_MONEY_TIME_INITIAL_VALUE 3.0
#define TIME_VS_MONEY_TIME_OBJECTIVE_NAME "Time spent"
#define TIME_VS_MONEY_MONEY_OBJECTIVE_NAME "Money gained"
#define TIME_VS_MONEY_INVEST_TIME_ACTION_NAME "Invest time"
#define TIME_VS_MONEY_STUDY_ACTION_NAME "Study"
