#define TRANSACTIONS_TEST_ENVIRONMNET_NAME "World"
#define TRANSACTIONS_TEST_NUMBER_OF_TIME_STEPS 3
#define TRANSACTIONS_TEST_TIME_STEP_NAME "Current Time-step"

#define TRANSACTIONS_TEST_PLAYER1_NAME "Player 1"
#define TRANSACTIONS_TEST_PLAYER2_NAME "Player 2"

#define TRANSACTIONS_TEST_OBJECTIVE_NAME "Objective"
#define TRANSACTIONS_TEST_RESOURCE1_NAME "Forks"
#define TRANSACTIONS_TEST_RESOURCE2_NAME "Spoons"

#define TRANSACTIONS_TEST_PLAYER1_RESOURCE1_INITIAL_QUANTITY 100.0
#define TRANSACTIONS_TEST_PLAYER1_RESOURCE2_INITIAL_QUANTITY 0.0

#define TRANSACTIONS_TEST_PLAYER2_RESOURCE1_INITIAL_QUANTITY 0.0
#define TRANSACTIONS_TEST_PLAYER2_RESOURCE2_INITIAL_QUANTITY 100.0

#define TRANSACTIONS_TEST_ACTION_NAME "Get forks and sell spoons"
#define TRANSACTIONS_TEST_ACTION_LOWER_BOUND -5.0
#define TRANSACTIONS_TEST_ACTION_UPPER_BOUND 5.0

#define TRANSACTIONS_TEST_PLAYER1_WILLINGNESS_TO_BUY_NAME "Player 1 wants this much forks"
#define TRANSACTIONS_TEST_PLAYER2_WILLINGNESS_TO_BUY_NAME "Player 2 wants this much forks"

#define TRANSACTIONS_TEST_APPROVAL_MESSAGE "Transaction approved"
#define TRANSACTIONS_TEST_REJECTION_MESSAGE "Transaction rejected"
#define TRANSACTIONS_TEST_REQUEST_MESSAGE "Request for transaction"




